from tkinter import *

window2 = Tk()
window2.geometry('197x130')
window2.title('Calculator')
window2.resizable(0,0)
window2.iconbitmap(r'D:\clash\files\xxx.ico')

button_name1 = Button(window2 , text='C' , bg='black',fg='white')
button_name1.grid(row=1 , column=1 , sticky='NWSE')
button_name2 = Button(window2 , text='=' , bg='blue',fg='white')
button_name2.grid(row=1 , column=2 , sticky='WNSE')
button_name3 = Button(window2 , text='-', bg='black',fg='white')
button_name3.grid(row=1 , column=4 ,sticky='WSNE')
button_name4 = Button(window2 , text='+', bg='black',fg='white')
button_name4.grid(row=2 , column=4 ,sticky='WNSE')
button_name5 = Button(window2 , text='%', bg='black',fg='white')
button_name5.grid(row=4 , column=4 , sticky='WSNE')
button_name6 = Button(window2 , text='÷', bg='black',fg='white')
button_name6.grid(row=3 , column=4 , columnspan=10 , sticky='WSNE')
button_name7 = Button(window2 , text='CE', bg='black',fg='white')
button_name7.grid(row=2, column=1 , sticky='W')
button_name8 = Button(window2 , text='7', width=2,height=1, bg='black',fg='white')
button_name8.grid(row=3 , column=1 , sticky='W')
button_name9 = Button(window2 , text='8', width=2,height=1, bg='black',fg='white')
button_name9.grid(row=3 , column=2 , sticky='WE')
button_name10 = Button(window2 , text='4', width=2,height=1, bg='black',fg='white')
button_name10.grid(row=4 , column=1 , sticky='WEN')
button_name11 = Button(window2, text='1', width=2,height=1, bg='black',fg='white')
button_name11.grid(row=5 , column=1 , sticky='W')
button_name12 = Button(window2, text='2', width=2,height=1, bg='black',fg='white')
button_name12.grid(row=5 , column=2 , sticky='WE')
button_name13 = Button(window2, text='5', width=2,height=1, bg='black',fg='white')
button_name13.grid(row=4 , column=2 , sticky='WE')
button_name14 = Button(window2, text='9', width=2,height=1, bg='black',fg='white')
button_name14.grid(row=3, column=3 , sticky='W')
button_name15 = Button(window2, text='6', width=2,height=1, bg='black',fg='white')
button_name15.grid(row=4 , column=3 , sticky='W')
button_name16 = Button(window2, text='3', width=2,height=1, bg='black',fg='white')
button_name16.grid(row=5 , column=3 , sticky='W')
button_name17 = Button(window2, text='0', width=2,height=1, bg='black',fg='white')
button_name17.grid(row=2 , column=3 , sticky='W')
button_name18 = Button(window2, text='/', width=2,height=1, bg='black',fg='white')
button_name18.grid(row=1 , column=3 , sticky='W')
button_name19 = Button(window2, text='√',width=2,height=1, bg='black',fg='white')
button_name19.grid(row=5 , column=4 , sticky='W')
entry_name = Entry(window2)
entry_name.grid(row = 2 , column=2 ,  sticky='WEN' )
# ============================================================
mainloop()